# Site settings
title: "Andy Kirk"
email: andy.kirk@gridlight-design.co.uk
description: "Portfolio and Blog."
baseurl: ""
url: "http://andykirk.github.io/"

# Defaults

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/


kramdown:
  auto_ids:       true
