# Site settings
title: "Andy Kirk"
email: andy.kirk@gridlight-design.co.uk
description: "Portfolio and Blog."
baseurl: ""
url: "http://andykirk.github.io/"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      role: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/


kramdown:
  auto_ids:       true
