# Site settings
title: "Andy Kirk"
email: "andy@andykirk.net"
description: "Portfolio and Blog."
repository: "andykirk/andykirk.github.io"
baseurl: ""
url: "http://andykirk.net"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      body_id: false
  -
    scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      poster: ""
      role: ""

# Build settings
markdown: kramdown
#permalink: /:year/:month/:title/
permalink: /:categories/:title/

kramdown:
  auto_ids:       true



exclude: ["node_modules", "bower_components", "Gemfile", "Gemfile.lock", "Gruntfile.js", "bower.json", "package.json", "README.md"]
