# Site settings
title: "Andy Kirk"
email: "andy@andykirk.net"
description: "Portfolio and Blog."
repository: "andykirk/andykirk.github.io"
baseurl: ""
url: "http://andykirk.net"
port: 4001

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      body_id: false
  -
    scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      poster: ""
      cloudinary_id: ""
      role: ""

# Build settings
markdown: kramdown
#permalink: /:year/:month/:title/
permalink: /:categories/:title/

kramdown:
  auto_ids:       true



exclude: [
    "_archive",
    "_images",
    "_scripts",
    "_styles",
    "bower.json",
    "bower_components",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "local-gulp.bat",
    "local-jekyll.bat",
    "node_modules",
    "package.json",
    "README.md"
]
